lang: ruby

rvm:
  - 2.4.0

before_install:
  - gem install bundler
  - bundle
  
script:
  - jekyll build -d buildto

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: buildto
  target_branch: master
  fqdn: morde.ir
  repo: nainemom-blog/nainemom-blog.github.io
  on:
    branch: master