# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: مرده
email: nainemom@gmail.com
name: مرده
description: تصور کن زندگیت در تخیلات یک مگس مرده باشد.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nainemom
github_username:  nainemom

# The release of Jekyll Now that you're using
version: v3.4.3
permalink: /:title/


# sass config
sass:
  style: :compressed
  sass_dir: _sass

# jekyll archives config
jekyll-archives:
  enabled:
  - tags
  - categories
  layout: archives
  permalinks:
    tags: '/tag/:name/'
    categories: '/category/:name/'

# paginate config
paginate: 5
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jalalidate
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.md
  - CNAME